apiVersion: v1
kind: Secret
metadata:
  name: proshop-backend-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_URI: "mongodb://mongodb-service.{{ .Values.namespace }}.svc.cluster.local:27017/proshop"
  JWT_SECRET: "CHANGE_ME_REPLACE_WITH_REAL_SECRET"
  PAYPAL_CLIENT_ID: "CHANGE_ME"
  PAYPAL_APP_SECRET: "CHANGE_ME"
  PAYPAL_API_URL: "https://api-m.sandbox.paypal.com"